export const carts_data = [
    // {
    //     id: 189,
    //     goods_id: 5231,
    //     goods_sn: null,
    //     color: "default",
    //     size: "F",
    //     sku: null,
    //     goods_attr: null,
    //     stock: 10,
    //     sys_sku: "e3a8d2ff843871ee799fbee936b7a5aa",
    //     goods: {
    //         id: 5231,
    //         type: "page",
    //         site_id: 13450,
    //         user_id: 0,
    //         url: "/index.php?id=5231",
    //         need_login: 0,
    //         module_id: 4908,
    //         module_list_id: 0,
    //         attr_code_cat: "Trousers",
    //         level: 1,
    //         state: null,
    //         cost: "1298.00",
    //         sort: 0,
    //         cid: 1,
    //         pid: 4907,
    //         is_dir: 0,
    //         ext: null,
    //         name_cn: "Agender破洞开叉牛仔裤",
    //         name_en: "AD1450101",
    //         view: null,
    //         create_time: "2019-11-23 17:01:27",
    //         update_time: "2019-11-23 17:02:02",
    //         expire_time: null,
    //         img: "/uploads/13450/5eecd5c56e5495c34849c7d64dfe47f7.jpg",
    //         desc: null,
    //         search_type: 0,
    //         configs: null,
    //         type_name: "开放",
    //         template: "product_post",
    //         state_name: null
    //     },
    //     num: 1,
    //     name_cn: "Agender破洞开叉牛仔裤",
    //     img: "/uploads/13450/5eecd5c56e5495c34849c7d64dfe47f7.jpg",
    //     price: "1298.00"
    // }
];

export const order_data = [
    // {
    //     id: 49,
    //     user_id: 3,
    //     order_sn: "Order201912061656308059",
    //     price: "1298.00",
    //     is_paid: 0,
    //     status: 0,
    //     shipping_sn: null,
    //     shipping_type: null,
    //     create_time: "2019-12-06 16:56:30",
    //     update_time: "2019-12-06 16:56:52",
    //     pay_time: null,
    //     name: "fu fei1",
    //     mobile: "2147483647",
    //     address: "beijin",
    //     status_name: "UNPAID",
    //     order_goods: [
    //         {
    //             id: 53,
    //             order_id: 49,
    //             order_sn: "Order201912061656308059",
    //             sys_sku: "e3a8d2ff843871ee799fbee936b7a5aa",
    //             num: 1,
    //             price: "1298.00",
    //             sku: {
    //                 id: 189,
    //                 goods_id: 5231,
    //                 goods_sn: null,
    //                 color: "default",
    //                 size: "F",
    //                 sku: null,
    //                 goods_attr: null,
    //                 stock: 10,
    //                 sys_sku: "e3a8d2ff843871ee799fbee936b7a5aa",
    //                 goods: {
    //                     id: 5231,
    //                     type: "page",
    //                     site_id: 13450,
    //                     user_id: 0,
    //                     url: "/index.php?id=5231",
    //                     need_login: 0,
    //                     module_id: 4908,
    //                     module_list_id: 0,
    //                     attr_code_cat: "Trousers",
    //                     level: 1,
    //                     state: null,
    //                     cost: "1298.00",
    //                     sort: 0,
    //                     cid: 1,
    //                     pid: 4907,
    //                     is_dir: 0,
    //                     ext: null,
    //                     name_cn: "Agender破洞开叉牛仔裤",
    //                     name_en: "AD1450101",
    //                     view: null,
    //                     create_time: "2019-11-23 17:01:27",
    //                     update_time: "2019-11-23 17:02:02",
    //                     expire_time: null,
    //                     img:
    //                         "/uploads/13450/5eecd5c56e5495c34849c7d64dfe47f7.jpg",
    //                     desc: null,
    //                     search_type: 0,
    //                     configs: null,
    //                     type_name: "开放",
    //                     template: "product_post",
    //                     state_name: null
    //                 }
    //             }
    //         }
    //     ]
    // },
    // {
    //     id: 49,
    //     user_id: 3,
    //     order_sn: "Order201912061656308059",
    //     price: "1298.00",
    //     is_paid: 0,
    //     status: 1,
    //     shipping_sn: null,
    //     shipping_type: null,
    //     create_time: "2019-12-06 16:56:30",
    //     update_time: "2019-12-06 16:56:52",
    //     pay_time: null,
    //     name: "fu fei1",
    //     mobile: "2147483647",
    //     address: "beijin",
    //     status_name: "UNPAID",
    //     order_goods: [
    //         {
    //             id: 53,
    //             order_id: 49,
    //             order_sn: "Order201912061656308059",
    //             sys_sku: "e3a8d2ff843871ee799fbee936b7a5aa",
    //             num: 1,
    //             price: "1298.00",
    //             sku: {
    //                 id: 189,
    //                 goods_id: 5231,
    //                 goods_sn: null,
    //                 color: "default",
    //                 size: "F",
    //                 sku: null,
    //                 goods_attr: null,
    //                 stock: 10,
    //                 sys_sku: "e3a8d2ff843871ee799fbee936b7a5aa",
    //                 goods: {
    //                     id: 5231,
    //                     type: "page",
    //                     site_id: 13450,
    //                     user_id: 0,
    //                     url: "/index.php?id=5231",
    //                     need_login: 0,
    //                     module_id: 4908,
    //                     module_list_id: 0,
    //                     attr_code_cat: "Trousers",
    //                     level: 1,
    //                     state: null,
    //                     cost: "1298.00",
    //                     sort: 0,
    //                     cid: 1,
    //                     pid: 4907,
    //                     is_dir: 0,
    //                     ext: null,
    //                     name_cn: "Agender破洞开叉牛仔裤",
    //                     name_en: "AD1450101",
    //                     view: null,
    //                     create_time: "2019-11-23 17:01:27",
    //                     update_time: "2019-11-23 17:02:02",
    //                     expire_time: null,
    //                     img:
    //                         "/uploads/13450/5eecd5c56e5495c34849c7d64dfe47f7.jpg",
    //                     desc: null,
    //                     search_type: 0,
    //                     configs: null,
    //                     type_name: "开放",
    //                     template: "product_post",
    //                     state_name: null
    //                 }
    //             }
    //         }
    //     ]
    // }
];

export const order_detail_data = {
    id: ""
    // id: 49,
    // user_id: 3,
    // order_sn: "Order201912061656308059",
    // price: "1298.00",
    // is_paid: 0,
    // status: 1,
    // shipping_sn: null,
    // shipping_type: null,
    // create_time: "2019-12-06 16:56:30",
    // update_time: "2019-12-06 16:56:52",
    // pay_time: null,
    // name: "fu fei1",
    // mobile: "2147483647",
    // address: "beijin",
    // status_name: "PAID",
    // order_goods: [
    //     {
    //         id: 53,
    //         order_id: 49,
    //         order_sn: "Order201912061656308059",
    //         sys_sku: "e3a8d2ff843871ee799fbee936b7a5aa",
    //         num: 1,
    //         price: "1298.00",
    //         sku: {
    //             id: 189,
    //             goods_id: 5231,
    //             goods_sn: null,
    //             color: "default",
    //             size: "F",
    //             sku: null,
    //             goods_attr: null,
    //             stock: 10,
    //             sys_sku: "e3a8d2ff843871ee799fbee936b7a5aa",
    //             goods: {
    //                 id: 5231,
    //                 type: "page",
    //                 site_id: 13450,
    //                 user_id: 0,
    //                 url: "/index.php?id=5231",
    //                 need_login: 0,
    //                 module_id: 4908,
    //                 module_list_id: 0,
    //                 attr_code_cat: "Trousers",
    //                 level: 1,
    //                 state: null,
    //                 cost: "1298.00",
    //                 sort: 0,
    //                 cid: 1,
    //                 pid: 4907,
    //                 is_dir: 0,
    //                 ext: null,
    //                 name_cn: "Agender破洞开叉牛仔裤",
    //                 name_en: "AD1450101",
    //                 view: null,
    //                 create_time: "2019-11-23 17:01:27",
    //                 update_time: "2019-11-23 17:02:02",
    //                 expire_time: null,
    //                 img: "/uploads/13450/5eecd5c56e5495c34849c7d64dfe47f7.jpg",
    //                 desc: null,
    //                 search_type: 0,
    //                 configs: null,
    //                 type_name: "开放",
    //                 template: "product_post",
    //                 state_name: null
    //             }
    //         }
    //     }
    // ]
};

export const address_data = [
    // {
    //     id: 13,
    //     user_id: 3,
    //     country_id: 0,
    //     country_name: "",
    //     state_id: 0,
    //     state_name: "",
    //     city_id: 0,
    //     city_name: "",
    //     address: "beijin",
    //     zip_code: "100000",
    //     mobile: "2147483647",
    //     is_default: 1,
    //     username: "fu fei1"
    // },
    // {
    //     id: 11,
    //     user_id: 3,
    //     country_id: 1,
    //     country_name: "中国",
    //     state_id: 4,
    //     state_name: "河北省",
    //     city_id: 40,
    //     city_name: "唐山市",
    //     address: "beijin",
    //     zip_code: "0",
    //     mobile: "2147483647",
    //     is_default: 0,
    //     username: "fu fei"
    // }
];

export const comment_list_data = [
    // {
    //     id: 31,
    //     user_id: 3,
    //     title: "TEST",
    //     desc: "",
    //     create_time: "2019-11-29 16:01:41",
    //     update_time: "2019-11-29 16:01:41",
    //     is_pass: 0,
    //     order_id: null,
    //     goods_id: null,
    //     imgs: ["/uploads/13450/fb9cdea1af746776d1186a1e280b0c48.jpg"]
    // },
    // {
    //     id: 2,
    //     user_id: 3,
    //     title: "first",
    //     desc: "",
    //     create_time: "2019-10-18 20:22:44",
    //     update_time: "2019-10-18 20:22:44",
    //     is_pass: 0,
    //     order_id: null,
    //     goods_id: null,
    //     imgs: null
    // },
    // {
    //     id: 1,
    //     user_id: 3,
    //     title: "first",
    //     desc: "",
    //     create_time: "2019-10-18 20:22:20",
    //     update_time: "2019-10-18 20:22:20",
    //     is_pass: 0,
    //     order_id: null,
    //     goods_id: null,
    //     imgs: null
    // }
];
